apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-pr-10
  labels:
    app.kubernetes.io/name: website-preview
    app.kubernetes.io/instance: pr-10
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx-public
  rules:
  - host: pr-10.website-preview.coppersoft.dev
    http:
      paths:
      - backend:
          service:
            name: website-pr-10
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - pr-10.website-preview.coppersoft.dev
      secretName: pr-10-website-preview.coppersoft.dev-tls
